name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy and run on EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu # Ubuntu 계열이면 ubuntu, Amazon Linux면 ec2-user
        run: |
          ssh $EC2_USER@$EC2_HOST '
            cd ~/autoTrading || git clone https://github.com/KIM-IMHONG/autoTrading.git ~/autoTrading && cd ~/autoTrading
            git pull
            source ~/autoTrading/venv/bin/activate || python3 -m venv ~/autoTrading/venv && source ~/autoTrading/venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt
            pkill -f "python main.py" || true
            nohup python main.py > bot.log 2>&1 &
          '
